########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: ${DOCKERDIR}/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: ${DOCKERDIR}/secrets/cf_dns_api_token
  postgres_default_password:
    file: ${DOCKERDIR}/secrets/postgres_default_password
  authentik_postgresql_user:
    file: ${DOCKERDIR}/secrets/authentik_postgresql_user
  authentik_postgresql_password:
    file: ${DOCKERDIR}/secrets/authentik_postgresql_password
  authentik_secret_key:
    file: ${DOCKERDIR}/secrets/authentik_secret_key

include:
    ########################### SERVICES
    # HOSTNAME defined in .env file
    #
    # Core services
  - compose/${HOSTNAME}/socket-proxy.yml
  - compose/${HOSTNAME}/traefik.yml
  - compose/${HOSTNAME}/portainer.yml
  - compose/${HOSTNAME}/postgresql.yml 
  - compose/${HOSTNAME}/authentik.yml 
  - compose/${HOSTNAME}/authentik-worker.yml
  - compose/${HOSTNAME}/wg-easy.yml
  #   #

  # Media services
#   - compose/${HOSTNAME}/plex.yml
  - compose/${HOSTNAME}/jellyfin.yml
  - compose/${HOSTNAME}/sonarr.yml
  - compose/${HOSTNAME}/huntarr.yml
  - compose/${HOSTNAME}/sabnzbd.yml
  - compose/${HOSTNAME}/radarr.yml
  - compose/${HOSTNAME}/prowlarr.yml
  - compose/${HOSTNAME}/tautulli.yml
  - compose/${HOSTNAME}/overseerr.yml
  - compose/${HOSTNAME}/profilarr.yml
#   - compose/${HOSTNAME}/netbox.yml
  - compose/${HOSTNAME}/nzbget.yml

