services:
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    profiles: ["media", "nzbget", "all"]
    restart: unless-stopped
    ports:
      - "6789:6789"
    volumes:
      - $DOCKERDIR/appdata/nzbget:/config
      - media_movies_rw:/movies
      - media_tvshows_rw:/tv 
      #- /path/to/downloads:/downloads #optional
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      NZBGET_USER: nzbget     #optional
      NZBGET_PASS: tegbzn6789 #optional
