services:
    profilarr:
        image: santiagosayshey/profilarr:latest # Use :beta for early access to new features
        container_name: profilarr
        profiles: ["media", "starr", "all"]
        ports:
            - 6868:6868
        volumes:
            - $DOCKERDIR/appdata/profilarr:/config
        environment:
          TZ: $TZ
        restart: unless-stopped