
services:
  # Radarr - Movies Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    profiles: ["media", "starr", "all"]
    networks:
      - default
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - media_movies_rw:/movies
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # DOCKER-LABELS-PLACEHOLDER