
services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  # Disable SABNnzbd's built-in HTTPS support for traefik proxy to work
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzdb
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "downloads", "all"]
    networks:
      - default
      - t3_proxy
    ports:
      - "8080:8080" 
    volumes:
      - $DOCKERDIR/appdata/sabnzbd:/config
      - media_movies_rw:/movies
      - media_tvshows_rw:/tv 
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      UMASK_SET: 002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web-internal"
      - "traefik.http.routers.portainer.rule=Host(`sabnzdb.$DOMAINNAME_1`)"
      - "traefik.http.routers.portainer.service=sabnzbd"
      - "traefik.http.routers.portainer.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.portainer.loadbalancer.server.port=8080"

volumes:
  media_movies_rw:
    name: media_movies_rw
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw"
      device: "192.168.1.112:/mnt/datastore/media/Movies"

  media_tvshows_rw:
    name: media_tvshows_rw
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw"
      device: "192.168.1.112:/mnt/datastore/media/TV Shows"
