services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    security_opt:
      - no-new-privileges:true
    profiles: ["media", "starr", "all"]
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/tautulli/config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID