services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["heimdall", "all"]
    volumes:
      - ${DOCKERDIR}/appdata/heimmdall/config:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      ALLOW_INTERNAL_REQUESTS: false #optional