services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "huntarr", "all"]
    networks:
      - t3_proxy
    ports:
      - "9705:9705"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/appdata/huntarr:/config
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huntarr.entrypoints=websecure-internal"
      - "traefik.http.routers.huntarr.rule=Host(`huntarr.jzcmyz.com`)"
      - "traefik.http.routers.huntarr.tls=true"
      - "traefik.http.services.huntarr.loadbalancer.server.port=9705"
      - "traefik.docker.network=t3_proxy"