services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    restart: 'unless-stopped'
    profiles: ["media", "jellyfin", "all"]
    # network_mode: host
    networks:
      - t3_proxy
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      JELLYFIN_PublishedServerUrl: https://jellyfin.jzcmyz.com #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/appdata/jellyfin/config:/config
      - media_movies_ro:/data/movies
      - media_tvshows_ro:/data/tvshows
      - media_home_movies_ro:/data/home_movies
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure-internal"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.jzcmyz.com`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=t3_proxy"

volumes:
  media_movies_ro:
    name: media_movies_ro
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,ro"
      device: "192.168.1.112:/mnt/datastore/media/Movies"

  media_tvshows_ro:
    name: media_tvshows_ro
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,ro"
      device: "192.168.1.112:/mnt/datastore/media/TV Shows"

  media_home_movies_ro:
    name: media_home_movies_ro
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,ro"
      device: "192.168.1.112:/mnt/datastore/media/Home Movies"