services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "nzbget", "all"]
    networks:
      - t3_proxy
    ports:
      - "6789:6789"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/appdata/nzbget:/config
      - ${DOCKERDIR}/appdata/nzbget/data:/data # for completed downloads and intermediate files
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      NZBGET_USER: nzbget     #optional
      NZBGET_PASS: tegbzn6789 #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=websecure-internal"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.${DOMAINNAME_1}`)"
      - "traefik.http.routers.nzbget.tls=true"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.docker.network=t3_proxy"      

volumes:
  media_movies_rw:
    name: media_movies_rw
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw"
      device: "192.168.1.112:/mnt/datastore/media/Movies"

  media_tvshows_rw:
    name: media_tvshows_rw
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw"
      device: "192.168.1.112:/mnt/datastore/media/TV Shows"

