services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "plex", "all"]
    # network_mode: "host"
    networks:
      - t3_proxy
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp" 
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/appdata/plex:/config
      - media_movies_ro:/media/movies
      - media_tvshows_ro:/media/tvshows
    environment:
      PLEX_UID: ${PUID}
      PLEX_GID: ${PGID}
      TZ: ${TZ}
      #HOSTNAME: ${PLEX_SERVER_NAME}
      PLEX_CLAIM: claim-7aupxjbbFzysj1oTw8b_ # Get a claim token from https://www.plex.tv/claim/ 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=web-internal"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAINNAME_1}`)"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.routers.plex.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"

volumes:
  media_movies_ro:
    name: media_movies_ro
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,ro"
      device: "192.168.1.112:/mnt/datastore/media/Movies"

  media_tvshows_ro:
    name: media_tvshows_ro
    driver: local
    driver_opts:
      type: "nfs"
      o: "nolock,soft,ro"
      device: "192.168.1.112:/mnt/datastore/media/TV Shows"