services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - t3_proxy 
    ports:
      - "8181:8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/appdata/tautulli/config:/config
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}